configs:
  docker:
    username: <username>
    password: <password>
  provision:
    tmpPath: /home/vagrant/tmp
  kube:
    configPath: /home/vagrant/tmp/kube.config
  cf:
    org: <organization>
    space: <space>
    domain: vcap.me