configs:
  docker:
    username: <username>
    password: <password>
  provision:
    tmpPath: /home/vagrant/tmp
    configPath: /home/vagrant/configs
  kube:
    configPath: /home/vagrant/configs/kube.config
  cf:
    org: <org>
    space: <space>
    domain: vcap.me