---
- name: Apply RabbitMQ operator
  become: true
  shell: |
    kubectl apply -f "https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml"
    sleep 10
  args:
    creates: "{{ TMP_DIR }}/rmq.success"

- name: Apply Cluster definitions
  become: true
  shell: | 
    kubectl apply -f /home/vagrant/cluster_configs/rabbitmq_cluster.yml
    sleep 15
  args:
    creates: "{{ TMP_DIR }}/rmq.success"

- name: Create placeholder file indicating successful RMQ setup
  file:
    path: "{{ TMP_DIR }}/rmq.success"
    state: touch

# shell: kubectl port-forward "service/local-rmq" --address 0.0.0.0 15672:15672 &